<#
.SYNOPSIS
    AmigaDevBox - Project Bootstrap Installer

.DESCRIPTION
    Downloads and sets up a new development project using AmigaDevBox.
    This script is meant to be run remotely via:
    irm https://github.com/vbuzzano/AmigaDevBox/raw/main/install.ps1 | iex

.NOTES
    Author: Vincent Buzzano (ReddoC)
    Date: December 2025
    Version: 0.1.0
#>

param(
    [string]$ProjectName,
    [string]$Description
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkMagenta
Write-Host "            🧙 DevBox Foundry v0.1.0 🧙" -ForegroundColor White
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkMagenta
Write-Host "Welcome to AmigaDevBox cross development toolKit !" -ForegroundColor Yellow
Write-Host "This wizard will set up your project with everything you need." -ForegroundColor Gray
Write-Host ""

# Check if git is installed (silent check)
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Host "❌ git is not installed" -ForegroundColor Red
    Write-Host ""
    Write-Host "Download git from: https://git-scm.com/download/win" -ForegroundColor Yellow
    Write-Host "Then run this script again after installation." -ForegroundColor Yellow
    exit 1
}

# Get project name
if (-not $ProjectName) {
    $ProjectName = Read-Host "Project Name"
    if (-not $ProjectName) {
        Write-Host "❌ Project name is required" -ForegroundColor Red
        exit 1
    }
}

# Get description
if (-not $Description) {
    $Description = Read-Host "Description (optional)"
}

# Sanitize project name - remove/replace invalid characters
$safeName = $ProjectName -replace '[/\\()^''":\[\]<>|?*]', '-'
# Remove trailing dots and spaces
$safeName = $safeName -replace '[\s.]+$', ''
$targetDir = Join-Path (Get-Location) $safeName

if (Test-Path $targetDir) {
    Write-Host "❌ Directory '$safeName' already exists" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Creating project '$ProjectName'..." -ForegroundColor Cyan
New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
Set-Location $targetDir

# Clone AmigaDevBox as .box
Write-Host "  ⏳ Cloning AmigaDevBox repository..." -ForegroundColor Cyan
git clone https://github.com/vbuzzano/AmigaDevBox.git .box 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Failed to clone AmigaDevBox" -ForegroundColor Red
    exit 1
}
Write-Host "  ✓ AmigaDevBox cloned to .box" -ForegroundColor Green

# Generate box.config.psd1 from template
Write-Host "  ⏳ Generating box.config.psd1..." -ForegroundColor Cyan
$templatePath = ".\.box\tpl\setup.config.template"
$configContent = Get-Content $templatePath -Raw
# Replace template values
$configContent = $configContent -replace 'Name\s*=\s*"[^"]*"', "Name = `"$ProjectName`""
$configContent = $configContent -replace 'Description\s*=\s*"[^"]*"', "Description = `"$Description`""
$configContent = $configContent -replace 'ProgramName\s*=\s*"[^"]*"', "ProgramName = `"$safeName`""
# Keep DefaultCPU = "m68020" and DefaultFPU = "" from template (don't replace)
Set-Content -Path "box.config.psd1" -Value $configContent -Encoding UTF8
Write-Host "  ✓ Generated box.config.psd1" -ForegroundColor Green

# Copy .box/box.ps1 to root (so user can run .\box.ps1 directly)
Write-Host "  ⏳ Setting up box.ps1..." -ForegroundColor Cyan
Copy-Item ".\.box\box.ps1" "box.ps1" -Force
Write-Host "  ✓ Copied box.ps1 to root" -ForegroundColor Green

# Copy .env.ps1 to .box/ (environment loader)
Copy-Item ".\.box\tpl\.env.ps1" ".\.box\.env.ps1" -Force

# Create .vscode directory with settings
Write-Host "  ⏳ Creating VS Code configuration..." -ForegroundColor Cyan
$vscodeDir = ".\.vscode"
New-Item -ItemType Directory -Path $vscodeDir -Force | Out-Null
Copy-Item -Path ".\.box\tpl\.vscode\*" -Destination $vscodeDir -Force -Recurse
Write-Host "  ✓ VS Code configuration created" -ForegroundColor Green

# Create .env file with project variables
Write-Host "  ⏳ Creating environment file..." -ForegroundColor Cyan
$envContent = @"
# Generated by AmigaDevBox installer
# Edit as needed for your project

# Project Information
PROJECT_NAME=$ProjectName
PROJECT_DESCRIPTION=$Description
PROGRAM_NAME=$safeName
VERSION=0.1.0

# Development Environment
DefaultCPU=m68020
DefaultFPU=

# Paths (customize as needed)
# VBCC_PATH=
# NDK_PATH=
# APOLLO_V4_HOST=
"@
Set-Content -Path ".env" -Value $envContent -Encoding UTF8
Write-Host "  ✓ Environment file created" -ForegroundColor Green

# Create README.md from template
Write-Host "  ⏳ Creating project README..." -ForegroundColor Cyan
$readmeTemplate = Get-Content ".\.box\tpl\README.template.md" -Raw
$readmeContent = $readmeTemplate -replace '{{PROJECT_NAME}}', $ProjectName
$readmeContent = $readmeContent -replace '{{PROJECT_DESCRIPTION}}', $Description
Set-Content -Path "README.md" -Value $readmeContent -Encoding UTF8
Write-Host "  ✓ README.md created" -ForegroundColor Green

Write-Host ""
Write-Host "✅ Project '$ProjectName' created successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Review and customize: box.config.psd1" -ForegroundColor White
Write-Host "  2. Initialize the project: .\box.ps1 init" -ForegroundColor White
Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkMagenta
Write-Host "       Happy coding on Amiga! 🎮" -ForegroundColor Yellow
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor DarkMagenta
Write-Host ""
Write-Host "📁 Project directory: $(Get-Location)" -ForegroundColor Cyan
